### ISSUE TITLE
Angular and Vue undefined

### ISSUE THREAD

**Issue by Nateowami** [ankitgaurav/perfect-tab#3]
I tried installing as per the instructions, but if I drag the top-level directory no manifest file is found, so the installation fails. So I drag in the `perfect-tab` directory and it installs, but immediately errors:

```
Uncaught ReferenceError: angular is not defined        perfect-tab.js:2
```

Or, if using the Vue branch:

```
Uncaught ReferenceError: Vue is not defined        main.js:8
```

Chromium 53 on Ubuntu 16.04.

The new tab page actually works though; it just logs this error on install. I haven't written any Chrome extensions in awhile, but I think because `perfect-tab.js` is loaded as a background script it is loaded before Angular or Vue, which is loaded by `perfect-tab.html`.

Not sure the solution though, but it seems errors should only happen if something is truly wrong.

Nice extension by the way! :tada:

**Comment by ankitgaurav** [comment]
I haven't noticed any such error in my machine as yet. However, I have removed the background script from Manifest file in the commit below:
ada5cc5cc99f65b5ab0251433baa918b05d1d4db

Please reinstall and check if the "Uncaught ReferenceError" persists.

Thanks btw :wink:

**Comment by Nateowami** [comment]
Yes, that fixes that error. :smile: Thanks. Another error cropped up, but I'll comment on the commit itself.
